namespace LiangWenPeak
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }

    [default_interface]
    runtimeclass ApiSettingsWindow : Microsoft.UI.Xaml.Window
    {
        ApiSettingsWindow();
    }
}
